/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["updatePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinics/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentClinic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/colleagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listColleagues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinic-members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createClinicMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPatients"];
        put?: never;
        post: operations["createPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPatient"];
        put?: never;
        post?: never;
        delete: operations["deletePatient"];
        options?: never;
        head?: never;
        patch: operations["updatePatient"];
        trace?: never;
    };
    "/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAppointments"];
        put?: never;
        post: operations["createAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/appointments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAppointment"];
        options?: never;
        head?: never;
        patch: operations["updateAppointment"];
        trace?: never;
    };
    "/v1/sms/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSMSTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sms/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendManualSMS"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                code: string;
                message: string;
            };
        };
        SuccessResponse: {
            /** @enum {boolean} */
            success: true;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            fullName: string;
            /** Format: uuid */
            clinicId: string;
        };
        UpdateProfileInput: {
            fullName: string;
            /** Format: email */
            email: string;
        };
        UpdatePasswordInput: {
            password: string;
        };
        Clinic: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        Colleague: {
            /** Format: uuid */
            id: string;
            fullName: string;
            /** Format: email */
            email: string;
            clinic: string;
            /** Format: date-time */
            joinedAt: string;
        };
        ColleagueListResponse: {
            data: components["schemas"]["Colleague"][];
        };
        CreateClinicMemberInput: {
            fullName: string;
            /** Format: email */
            email: string;
            temporaryPassword: string;
        };
        /** @enum {string} */
        PatientStatus: "active_treatment" | "completed" | "cancelled" | "waiting" | "inactive";
        Patient: {
            /** Format: uuid */
            id: string;
            fullName: string;
            phone: string;
            status: components["schemas"]["PatientStatus"];
            treatmentNote?: string;
            internalNote?: string;
            remindersEnabled: boolean;
            reminderDaysBefore: number[];
            reminderSendHour: number;
            /** Format: date-time */
            nextAppointment?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PatientInput: {
            fullName: string;
            phone: string;
            status: components["schemas"]["PatientStatus"];
            treatmentNote?: string;
            internalNote?: string;
            remindersEnabled?: boolean;
            reminderDaysBefore?: number[];
            reminderSendHour?: number;
        };
        PatientListResponse: {
            data: components["schemas"]["Patient"][];
        };
        /** @enum {string} */
        AppointmentStatus: "planned" | "confirmed" | "completed" | "cancelled" | "no_show";
        Appointment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            patientId: string;
            /** Format: uuid */
            doctorUserId?: string;
            /** Format: date-time */
            startsAt: string;
            status: components["schemas"]["AppointmentStatus"];
            note?: string;
        };
        AppointmentInput: {
            /** Format: uuid */
            patientId: string;
            /** Format: uuid */
            doctorUserId?: string;
            /** Format: date-time */
            startsAt: string;
            status: components["schemas"]["AppointmentStatus"];
            note?: string;
        };
        AppointmentListResponse: {
            data: components["schemas"]["Appointment"][];
        };
        SMSTemplate: {
            /** Format: uuid */
            id: string;
            key: string;
            title: string;
            body: string;
            enabled: boolean;
        };
        SMSTemplateListResponse: {
            data: components["schemas"]["SMSTemplate"][];
        };
        SendManualSMSInput: {
            /** Format: uuid */
            patientId: string;
            /** Format: uuid */
            appointmentId?: string;
            /** Format: uuid */
            templateId: string;
        };
        SendSMSResponse: {
            /** Format: uuid */
            messageId: string;
            /** @enum {string} */
            status: "queued" | "sent" | "failed";
        };
        /** @enum {string} */
        AuditEntityType: "patient" | "appointment" | "sms_template" | "sms_message" | "notification_setting" | "clinic_member";
        AuditLog: {
            /** Format: uuid */
            id: string;
            action: string;
            summary: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuditLogListResponse: {
            data: components["schemas"]["AuditLog"][];
        };
    };
    responses: {
        /** @description Stable error response. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API health status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileInput"];
            };
        };
        responses: {
            /** @description Updated current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    updatePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordInput"];
            };
        };
        responses: {
            /** @description Password updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getCurrentClinic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current clinic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clinic"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listColleagues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clinic colleagues. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColleagueListResponse"];
                };
            };
        };
    };
    createClinicMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClinicMemberInput"];
            };
        };
        responses: {
            /** @description Created clinic member. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Colleague"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    listPatients: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clinic patients. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientListResponse"];
                };
            };
        };
    };
    createPatient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientInput"];
            };
        };
        responses: {
            /** @description Created patient. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getPatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deletePatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient soft deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    updatePatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientInput"];
            };
        };
        responses: {
            /** @description Updated patient. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
        };
    };
    listAppointments: {
        parameters: {
            query?: {
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clinic appointments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentListResponse"];
                };
            };
        };
    };
    createAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentInput"];
            };
        };
        responses: {
            /** @description Created appointment. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
        };
    };
    deleteAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Appointment soft deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentInput"];
            };
        };
        responses: {
            /** @description Updated appointment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
        };
    };
    listSMSTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clinic SMS templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SMSTemplateListResponse"];
                };
            };
        };
    };
    sendManualSMS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendManualSMSInput"];
            };
        };
        responses: {
            /** @description SMS send result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendSMSResponse"];
                };
            };
            502: components["responses"]["Error"];
        };
    };
    listAuditLogs: {
        parameters: {
            query: {
                entityType: components["schemas"]["AuditEntityType"];
                entityId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity audit logs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
        };
    };
}
